# Generated by Django 4.0.1 on 2022-05-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=3)),
                ('p1_id', models.CharField(max_length=3)),
                ('p2_id', models.CharField(max_length=3)),
                ('p3_id', models.CharField(max_length=3)),
                ('p4_id', models.CharField(max_length=3)),
                ('p5_id', models.CharField(max_length=3)),
                ('p6_id', models.CharField(max_length=3)),
            ],
        ),
    ]
