# Generated by Django 4.0.1 on 2022-05-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_team', '0003_alter_team_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='user_id',
            field=models.CharField(max_length=3),
        ),
    ]
