# Generated by Django 4.0.1 on 2022-05-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_team', '0004_alter_team_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='p1_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='p2_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='p3_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='p4_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='p5_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='p6_id',
        ),
        migrations.AddField(
            model_name='team',
            name='game',
            field=models.CharField(default='yellow', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='p1',
            field=models.CharField(default='pikachu', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='p2',
            field=models.CharField(default='pikachu', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='p3',
            field=models.CharField(default='pikachu', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='p4',
            field=models.CharField(default='pikachu', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='p5',
            field=models.CharField(default='pikachu', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='p6',
            field=models.CharField(default='pikachu', max_length=255),
            preserve_default=False,
        ),
    ]
