# Generated by Django 4.0.1 on 2022-05-13 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('build_team', '0007_team_p1_id_team_p1_sprite_team_p2_id_team_p2_sprite_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
