# Generated by Django 4.0.1 on 2022-05-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('build_team', '0008_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=3)),
                ('pk_ids', models.CharField(max_length=255)),
                ('game', models.CharField(max_length=255)),
            ],
        ),
    ]
