# Generated by Django 4.0.1 on 2022-05-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_team', '0011_leader_location_reward_remove_team_user_id_team_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reward',
            name='name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reward',
            name='type',
            field=models.CharField(default='type', max_length=255),
            preserve_default=False,
        ),
    ]
