# Generated by Django 4.0.1 on 2022-06-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_team', '0013_leader_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('gen', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('has_gyms', models.BooleanField()),
            ],
        ),
    ]
