# Generated by Django 4.0.1 on 2022-06-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_team', '0014_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=12),
            preserve_default=False,
        ),
    ]
