# Generated by Django 4.0.1 on 2022-06-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_team', '0016_game_gen_roman'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='group_name',
            field=models.CharField(default='red', max_length=255),
            preserve_default=False,
        ),
    ]
