# Generated by Django 4.0.1 on 2022-06-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_team', '0017_game_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='game_txt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='game_txt',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
