# Generated by Django 4.0.1 on 2022-06-04 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('build_team', '0018_gym_game_txt_team_game_txt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='game',
        ),
    ]
