# Generated by Django 4.0.1 on 2022-06-04 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('build_team', '0021_remove_team_game_alter_gym_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='game_txt',
        ),
        migrations.AddField(
            model_name='team',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='build_team.game'),
            preserve_default=False,
        ),
    ]
