# Generated by Django 4.0.1 on 2022-06-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_team', '0022_remove_team_game_txt_team_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='leader',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
