# Generated by Django 4.0.1 on 2022-06-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_team', '0023_alter_game_name_alter_leader_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
